//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFCloudClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CFCloudClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete failed. Please wait a moment and retry. 的本地化字符串。
        /// </summary>
        internal static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this file? 的本地化字符串。
        /// </summary>
        internal static string FileDeleteConfirm {
            get {
                return ResourceManager.GetString("FileDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file you selected exists. Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this folder and all the files in it? 的本地化字符串。
        /// </summary>
        internal static string FolderDeleteConfirm {
            get {
                return ResourceManager.GetString("FolderDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.58.187.140:5001 的本地化字符串。
        /// </summary>
        internal static string HeartBeatHost {
            get {
                return ResourceManager.GetString("HeartBeatHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.58.187.140:6060 的本地化字符串。
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your new folder name: 的本地化字符串。
        /// </summary>
        internal static string InputFolderName {
            get {
                return ResourceManager.GetString("InputFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string LastNameEmpty {
            get {
                return ResourceManager.GetString("LastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User not registered. 的本地化字符串。
        /// </summary>
        internal static string LoginFailEmail {
            get {
                return ResourceManager.GetString("LoginFailEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password error. 的本地化字符串。
        /// </summary>
        internal static string LoginFailPassword {
            get {
                return ResourceManager.GetString("LoginFailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login fail. Unknown error. 的本地化字符串。
        /// </summary>
        internal static string LoginFailUnknown {
            get {
                return ResourceManager.GetString("LoginFailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not select a file. 的本地化字符串。
        /// </summary>
        internal static string NotaFile {
            get {
                return ResourceManager.GetString("NotaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The two passwords you typed are not the same. 的本地化字符串。
        /// </summary>
        internal static string PasswordConfirmError {
            get {
                return ResourceManager.GetString("PasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal path or access fail. 的本地化字符串。
        /// </summary>
        internal static string PathIllegal {
            get {
                return ResourceManager.GetString("PathIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CFCloud 的本地化字符串。
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email is used. 的本地化字符串。
        /// </summary>
        internal static string RegisterFailEmail {
            get {
                return ResourceManager.GetString("RegisterFailEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register fail. Unknown error. 的本地化字符串。
        /// </summary>
        internal static string RegisterFailUnknown {
            get {
                return ResourceManager.GetString("RegisterFailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename failed. Please wait a moment and retry. 的本地化字符串。
        /// </summary>
        internal static string RenameFail {
            get {
                return ResourceManager.GetString("RenameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your new name: 的本地化字符串。
        /// </summary>
        internal static string RenameText {
            get {
                return ResourceManager.GetString("RenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type the email of whom your want to share: 的本地化字符串。
        /// </summary>
        internal static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path selected is alreadly exists and is not empty. Do you want to delete all files under this path? 的本地化字符串。
        /// </summary>
        internal static string WorkspaceExist {
            get {
                return ResourceManager.GetString("WorkspaceExist", resourceCulture);
            }
        }
    }
}
